apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: math28-postgresql-pvc
  namespace: math28
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard   # Minikube default StorageClass
